### PR TITLE
Adding more characters to the dictionary

### PR DESCRIPTION
**Pull request by shidhincr**
Adding more characters to the dictionary

### CODE REVIEW

**Comment by TiTi** [comment]
Why not, even if this add a new character : /
You should checkout :
http://discogscounter.getfreehosting.co.uk/js-noalnum.php
http://utf-8.jp/public/jsfuck.html
https://github.com/TShadwell/Horrible.js

**Comment by shidhincr** [comment]
Oh .. cool .. thanks for the links

**Comment by TiTi** [comment]
Also: http://www.jsfuck.com/
https://www.youtube.com/watch?feature=player_embedded&v=RTxtiLp1C8Y

**Comment by shidhincr** [comment]
Saw the JSFuck.com  already .. :)

**Pull request merged**
